commit
Julia3202/java-filmorate pull request #2
Opened 2023-06-08 21:57 UTC by Julia3202

Добавила классы

2023-06-12 20:31 UTC, Frilock requested changes
Добрый вечер, довольно много комментариев получилось оставить в этот раз. Опять же у вас не проходят тесты в сборке на GitHub, но у вас в коде есть явные ошибки, которые возможно, являются причиной ошибок в тестах. Поправьте их. Постарался довольно подробно написать комментарии к работе. Нужно подразобраться, попыхтеть и дальше будет легче.

2023-06-12 20:31 UTC, Frilock commented on pom.xml
> +			<version>1.18.20</version>
Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${example-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2023-06-12 20:31 UTC, Frilock commented on pom.xml
> +			<groupId>org.microprofile-ext.restclient-ext</groupId>
Я думаю вам не нужна данная библиотека, если хотите обрабатывать исключения так, то можете воспользоваться этой статьей https://struchkov.dev/blog/ru/exception-handling-controlleradvice/

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +
Лишняя пустая строка

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
Лишняя пустая строка

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void setId(int id) {
Зачем вам сеттер и геттер, если вы над классом вешаете эти аннотации? Данные методы будут и так доступны

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(String name, String description, LocalDate releaseDate, long duration) {
Чтобы не создавать такой громоздкий конструктор, можно воспользоваться аннотацией RequiredArgsConstructor или AllArgsConstructor, от lombok. И данный конструктор будет создан не явно

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +//@Builder.Default
Закомментированного кода быть не должно

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +
Лишняя строчка

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +  /*  public void setEmail(String email) {
Аналогичные комментарии

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserValidation validation = new UserValidation();
Тут минимум должен быть приватный модификатор

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public int generateId() {
Данный метод лучше сделать статичным, поскольку он меняет поле класса (вам по идее IDEA должна такое подсказать)

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final Map<String, User> userEmail = new HashMap<>();
А для чего Вам хранить данную мапу? Это излишне как мне кажется. Вот у вас есть user, у него поле email оттуда его и берите

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PostMapping(value = "/users")
Все ваши публичные методы имеют в своем пути /users, чтобы не писать его над каждым методом можно указать данный путь в аннотации RequestMapping(value = ....) и все публичные методы будут иметь такой префикс

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getName() == null) {
Вам также нужно проверять что getName не вернет пустую строку, для этого можно воспользоваться библиотекой StringUtils.isBlank, от apache common 3. В данной библиотеке содержится много полезных методов

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (exsistByEmail != null && exsistByEmail != exsist) {
Вообще вы создаете отдельный класс для валидации ну все равно методы create и update выглядят громоздко. По хорошему Вам нужно сделать что то такое
validator.check(user) {
 throw new ...
}
...

Название метода привел ради примера.

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +    public ValidationException(String s) {
Лучше поле назвать message

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends Throwable{
Как вы уже проходили ранее свои "кастомные" исключения, правильнее наследовать от RuntimeException

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Кроме того, вам нужно проверять что дата заполнена, иначе вы тут получите NPE

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +    public boolean validReleaseDate(Film film) throws ValidationException {
По мимо этого LocalDate.of(1895, 12, 28) - это какое то магическое значение, такие принято выносить в константы класса - private static final LocalDate....

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +        }else{
Не верное кол-во отступов. Нужно привести код в соответствии к Code Style. Для этого можете в каждом классе выполнять комбинацию Cntrl+alt + L. Либо можете установить плагин в IDEA - sonarlynt это статический анализатор кода, он покажет ряд хороших практик

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +        } else if(film. getReleaseDate() == null){
Вот смотрите, во первых, после точки лишний пробел. Вы с третьей работы уже должны писать приложения в соответствии с Java Code Style, какой смысл мне каждый раз присылать работу с данной проблемой ?) 
Во вторых, смотрите у вас в первом if - film.getReleaseDate().isBefore, а во втором film. getReleaseDate() == null
Так вы получите ошибку, в случае когда getReleaseDate вернет null. У вас будет null.isBefore - NPE.
Возможно отсюда тесты и не проходят

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +        } else if(film. getDescription() == null){
Аналогично

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +        if ((film.getName().isBlank()) || film.getName() == null) {
Проверки происходят слева на право, тут будет ошибка.

2023-06-12 20:31 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/validation/FilmValidationTest.java
> +
Лишний пропуск строки

2023-06-12 20:31 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/validation/FilmValidationTest.java
> +        Film film2 = new Film("testName", "testDescription", date, 120);
Числовые префиксы и окончания давать локальным переменным не принято

2023-06-12 20:31 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/validation/UserValidationTest.java
> +
Лишние пробелы

2023-06-12 20:31 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/validation/UserValidationTest.java
> +        System.out.println(result4);
System.out.println в приложениях использовать не нужно. Используйте его для отладки, но в итоговый код включать не нужно

2023-06-12 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validation/UserValidation.java
> +public class UserValidation {
Комментарии в данном классе аналогичны комментариям в предыдущем валидаторе

2023-06-13 11:43 UTC, Julia3202 commented on pom.xml
> +			<version>1.18.20</version>
В теории было описано так.

2023-06-13 11:58 UTC, Julia3202 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final Map<String, User> userEmail = new HashMap<>();
Пользователь может поменять почту. Это с рекомендации наставника было сделано.

2023-06-13 17:21 UTC, Frilock requested changes
Оставил еще ряд комментариев

2023-06-13 17:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else {
Вот смотрите, у вас конструкция такая:
if (условие) {
....
return
} else {
...
}

Вот в данном случае else не нужно, можно просто 
if (уловие) {
...
return
} 
....
Надеюсь почему вы поняли.
То есть смысл претензии какой - не должно быть лишних if или else.
Вообще можно условие инвертировать (сделать обратным) и тогда код будет еще локаничнее и будет меньше "вложенности"

2023-06-13 17:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else {
Кроме того условия внутри if можно объединить в 1. например, validator.validate(...)

2023-06-13 17:21 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("exception");
В третьих, вы исключения которые кидаете пишете для себя или для пользователя, который потом их увидит. Там нужно писать какое то вменяемое сообщение. что за ошибка и почему она произошла. Всякий бред там писать не надо)

2023-06-13 17:21 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/validation/FilmValidationTest.java
> +
Лишние пропусти строк

2023-06-13 17:21 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/validation/FilmValidationTest.java
> +        LocalDate date2 = LocalDate.of(2021, 10, 5);
Префиксы и окончания числовые не приветствуются в названии переменных

2023-06-14 15:45 UTC, Julia3202 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else {
Удалять все if-else не стала,мне понятнее что и почему работает именно так, если Вы не против,то оставлю так.

2023-06-14 20:31 UTC, Frilock approved these changes
Добрый день, я работу принял, но есть те места которые мне не нравятся. Я в следующей работе буду на них внимания обращать тоже.

2023-06-14 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (validation.validation(user)) {
Метод было бы логичнее назвать validate

2023-06-14 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +        if (film.getDescription() == null || film.getDescription().isBlank()) {
StringUtils.isBlank(...) заменяет обе проверки, причем их можно обьединить и с проверкой ниже, потому что проверки film.getDescription().isBlank() и film.getDescription().length() > 200 проверяют одно и тоже по сути

2023-06-14 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +
Между методами 1 строчка

2023-06-14 20:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/validation/UserValidation.java
> +            throw new ValidationException("Валидация не была пройдена.");
Аналогично

2023-06-16 09:42 UTC, merged